<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>LabGuardServer.Core</RootNamespace>
    <AssemblyName>LabGuardServer.Core</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Web.Extensions" />
    <Reference Include="System.Security" />
    <Reference Include="System.Configuration" />
  </ItemGroup>

</Project>
